https://data.wprdc.org/dataset/market-value-analysis-2021

# Most Expensive Housing Neighborhood in Allegany County

![done!](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYWRlamowd3IwMHpsNnpqejFicnNuNmpwZm45NXhkdDc2eDNqNXpmNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/UqqVRaP8y4uo1GNxbN/giphy.gif)

With the data from the 2013 American Community Survey, our group believes that the assumption of the "Best Housing" should consider the worth of the average house in each neighborhood. In most cases, the best living quarters are typically the ones more expensive due to those ones typically being the ones with the most upgrades, renovations, etc. Before we were able to narrow it down, we coded a visualization of the CSV file and then located the top 5 income brackets in order to fully narrow it down. Then, we would calculate the most expensive neighborhood by calculating how many houses run into those brackets.

In [44]:
import pandas as pd

# Attempt to load the file from the specified directory
file_path = "/Users/emily/Documents/value.csv"
data = pd.read_csv(file_path)

# Display the first few rows to confirm successful loading
data.head(25)

,Neighborhood,Id,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999","Margin of Error; Total: - $15,000 to $19,999",...,"Estimate; Total: - $300,000 to $399,999","Margin of Error; Total: - $300,000 to $399,999","Estimate; Total: - $400,000 to $499,999","Margin of Error; Total: - $400,000 to $499,999","Estimate; Total: - $500,000 to $749,999","Margin of Error; Total: - $500,000 to $749,999","Estimate; Total: - $750,000 to $999,999","Margin of Error; Total: - $750,000 to $999,999","Estimate; Total: - $1,000,000 or more","Margin of Error; Total: - $1,000,000 or more"
0,Allegheny Center,1,38.0,19.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
1,Allegheny West,2,77.0,34.000000,6.0,9.000000,0.0,10.000000,0.0,10.000000,...,17.0,19.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,6.0,9.000000
2,Allentown,3,575.0,124.004032,48.0,36.400549,19.0,21.840330,32.0,33.166248,...,0.0,17.320508,0.0,17.320508,5.0,16.248077,0.0,17.320508,0.0,17.320508
3,Arlington,4,469.0,93.866927,6.0,17.320508,16.0,19.339080,6.0,17.320508,...,0.0,17.320508,0.0,17.320508,0.0,17.320508,0.0,17.320508,2.0,14.696938
4,Arlington Heights,5,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
5,Banksville,6,980.0,116.773285,28.0,36.386811,0.0,20.000000,0.0,20.000000,...,14.0,28.792360,0.0,20.000000,0.0,20.000000,0.0,20.000000,15.0,30.413813
6,Bedford Dwellings,7,51.0,37.000000,0.0,10.000000,5.0,8.000000,9.0,13.000000,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
7,Beechview,8,2043.0,189.261724,0.0,31.622777,0.0,31.622777,0.0,31.622777,...,0.0,31.622777,0.0,31.622777,0.0,31.622777,7.0,32.310989,0.0,31.622777
8,Beltzhoover,9,543.0,126.198257,4.0,19.078784,0.0,20.000000,75.0,59.506302,...,0.0,20.000000,0.0,20.000000,0.0,20.000000,0.0,20.000000,0.0,20.000000
9,Bloomfield,10,1650.0,149.338542,5.0,30.805844,18.0,33.466401,23.0,35.000000,...,101.0,47.958315,25.0,37.802116,21.0,38.078866,0.0,31.622777,0.0,31.622777
10,Bluff,11,119.0,53.525695,0.0,20.000000,6.0,19.519221,10.0,19.519221,...,5.0,18.681542,0.0,20.000000,0.0,20.000000,0.0,20.000000,0.0,20.000000
11,Bon Air,12,310.0,59.000000,3.0,5.000000,10.0,15.000000,0.0,10.000000,...,0.0,10.000000,5.0,16.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
12,Brighton Heights,13,2219.0,173.893646,9.0,28.722813,0.0,26.457513,0.0,26.457513,...,0.0,26.457513,0.0,26.457513,0.0,26.457513,0.0,26.457513,0.0,26.457513
13,Brookline,14,4376.0,323.978394,54.0,47.989582,39.0,47.095647,5.0,38.262253,...,11.0,41.521079,0.0,38.729833,8.0,41.097445,22.0,52.621288,8.0,39.293765
14,California-Kirkbride,15,85.0,31.000000,0.0,10.000000,9.0,9.000000,0.0,10.000000,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
15,Carrick,16,2660.0,223.861564,9.0,35.284558,36.0,40.236799,42.0,62.425956,...,15.0,42.720019,0.0,36.055513,7.0,36.660606,0.0,36.055513,0.0,36.055513
16,Central Business District,17,402.0,103.344085,0.0,24.494897,0.0,24.494897,0.0,24.494897,...,11.0,25.159491,37.0,39.420807,83.0,70.887234,10.0,28.089144,10.0,26.925824
17,Central Lawrenceville,18,1055.0,123.211201,0.0,24.494897,13.0,26.381812,0.0,24.494897,...,28.0,33.541020,12.0,24.103942,10.0,27.495454,0.0,24.494897,0.0,24.494897
18,Central Northside,19,627.0,104.359954,10.0,15.099669,0.0,17.320508,4.0,16.248077,...,71.0,35.057096,21.0,18.973666,0.0,17.320508,0.0,17.320508,0.0,17.320508
19,Central Oakland,20,197.0,62.777384,0.0,17.320508,0.0,17.320508,0.0,17.320508,...,11.0,22.113344,0.0,17.320508,0.0,17.320508,0.0,17.320508,10.0,20.615528
20,Chartiers City,21,166.0,57.000000,0.0,10.000000,9.0,13.000000,0.0,10.000000,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
21,Chateau,22,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
22,Crafton Heights,23,1014.0,115.477270,9.0,21.656408,6.0,19.519221,32.0,36.386811,...,0.0,20.000000,0.0,20.000000,0.0,20.000000,0.0,20.000000,0.0,20.000000
23,Crawford-Roberts,24,290.0,80.603970,10.0,18.867962,10.0,18.867962,0.0,14.142136,...,0.0,14.142136,0.0,14.142136,0.0,14.142136,0.0,14.142136,0.0,14.142136
24,Duquesne Heights,25,812.0,100.005000,6.0,14.866069,10.0,18.027756,0.0,14.142136,...,64.0,39.293765,30.0,28.425341,4.0,12.206556,0.0,14.142136,7.0,14.866069

In [58]:
# Define columns that correspond to high-income brackets
high_income_brackets = [
    'Estimate; Total: - $300,000 to $399,999',
    'Estimate; Total: - $400,000 to $499,999',
    'Estimate; Total: - $500,000 to $749,999',
    'Estimate; Total: - $750,000 to $999,999',
    'Estimate; Total: - $1,000,000 or more'
]

# Calculate the total Most Expensive Housing estimate for each neighborhood
data['Most Expensive Housing'] = data[high_income_brackets].sum(axis=1)

# Sort neighborhoods by the Most Expensive Housing total in descending order and select the top 10
top_10_expensive_neighborhoods = data[['Neighborhood', 'Most Expensive Housing']].sort_values(by='Most Expensive Housing', ascending=False).head(10)

# Display the result
top_10_expensive_neighborhoods

                 Neighborhood  Most Expensive Housing
76        Squirrel Hill North                  1427.0
77        Squirrel Hill South                  1364.0
68                  Shadyside                   966.0
63               Point Breeze                   733.0
39              Highland Park                   454.0
72           South Side Flats                   244.0
56              North Oakland                   180.0
16  Central Business District                   151.0
9                  Bloomfield                   147.0
53           Mount Washington                   129.0

# Our Results
According to our dataset script, the most expensive housing is in Squirrel Hill North. This could lead us to assume that Squirrel Hill is considered one of the best neighborhoods with the best houses.

![done!](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdnJvbzB2eDczeDFyZTA2czY1eHh4YXQydno1NGJvZ3czdmlpc3hpNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/1SvnHJFEuEH7hp81tF/giphy.gif)